### ISSUE TITLE
Should refresh rate for interlaced video be doubled?

### ISSUE THREAD

**Issue by kkkrackpot** [lvml/mpv-plugin-xrandr#12]
Hi,

Please have a look on my issue on mpv's tracker https://github.com/mpv-player/mpv/issues/4010

Shouldn't the script set doubled refresh rate for interlaced video (i.e. 50Hz for 25fps, 59.94Hz for 29.97fps, and 60Hz for 30fps) ?

Unfortunately, I don't know much about interlacing, telecine, pulldown, etc. I can only note, that 25 fps progressive video certainly looks good on 25 Hz TV, but the mentioned 25 interlaced video seems better on 60Hz monitor.

Regards,
Alex

**Comment by lvml** [comment]
The sample file you linked in https://github.com/mpv-player/mpv/issues/4010 is not "interlaced" in the sense that it has alternating fields, two of which constitute one frame. Instead, that video has undergone some weird conversion from a different original frame rate, such that only every Nth frame looks like it is composed of two "fields" interleaved in a comb-like fashion. This might be something known as "telecine" or "pullup" conversion.

I have read that ffmpeg has lots of different "de-interlacing" and "inverse telecine" filters you could try, some of them also seem to address the issue of videos that were transferred from a different original frame rate - but I am not at all an expert on this - I never work with interlaced videos.

If you just want to get rid of interlacing-style comb artefacts, you could use `mpv --vf=lavfi=kerndeint `, but since you mention loss of frames, you are probably more looking for fixing temporal than spatial issues in playing back this file. I'm afraid I can't help you with this - to me it looks like that video is quite simply suffering from a conversion that was done before you recorded it, and I do not know how to reverse the effects of that.

With regards to "should xrandr use twice the refresh rate for interlaced content": That would make sense only if either your display was actually an interlaced one (like CRT), which is highly unlikely these days.
I assume that if you used a de-interlacing filter that tries to deliver "one frame per field" (like yadif does per default), the xrandr script would be signaled the higher framerate of the filtered video - but I'm not sure about this, and I don't have any (real) interlaced video to test that theory.

**Comment by kkkrackpot** [comment]
Actually, I don't know how they made that video, it must be a TV capture or something. I thought it's interlaced because in mediainfo it says `Scan type Interlaced, Store method separated fields, Scan order top field first`. But it doesn't show comb errors, and enabled deinterlacing (mpv's `d` button) only makes frame-drops worse.

It seems the video itself is so weird that little can be done with messing around playback options...

Anyway, thanks for looking into my issue!

Regards,
Alex
