### ISSUE TITLE
Support for resolution change

### ISSUE THREAD

**Issue by ypnos** [lvml/mpv-plugin-xrandr#6]
This is the output of my xrandr:

> Screen 0: minimum 320 x 200, current 2560 x 1440, maximum 8192 x 8192
> DP-1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 553mm x 311mm
>    2560x1440     59.95*+
>    2048x1152     60.00
>    1920x1200     59.88
>    1920x1080     60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98
>    1920x1080i    60.00    50.00    59.94
>    1600x1200     60.00
>    1680x1050     59.95
>    1280x1024     75.02    60.02
>    1200x960      59.99
>    1152x864      75.00
>    1280x720      60.00    50.00    59.94
>    1024x768      75.03    60.00
>    800x600       75.00    60.32
>    720x576       50.00
>    720x480       60.00    59.94
>    640x480       75.00    60.00    59.94
>    720x400       70.08

As you can see, all commonly used framerates are supported, but only in full hd resolution.
It would be great if your plugin could also automatically change the resolution if the current one does not support the refresh rate needed. Maybe via config option?

**Comment by lvml** [comment]
Changing to one specific "favorite" resolution that the user configured himself should be fairly easy to implement. Choosing a "best compromise of resolution versus available display refresh rates at that resolution" however would be highly non-trivial.

So would you be happy if xrandr.lua was just extended with an option to change to your favourite 1920x1080 resolution (and back after playing)?

BTW: Are you sure your display has a native resolution of 2560x1440 pixels? I ask because I wonder why any manufacturer should create a display that supports less refresh rates at its native resolution than with ones that need scaling...

**Comment by ypnos** [comment]
That would be a tremendous help.
A bonus would be to only do it if the current resolution doesn't support the desired rate.
I doubt anyone would need anything more than that.

**Comment by lvml** [comment]
I implemented --script-opts=xrandr-output-mode=... in https://github.com/lvml/mpv-plugin-xrandr/commit/bd9a1427a90f0e66170b6bdeaf1749018865bd6d - please try.

**Comment by ypnos-web** [comment]
Yes, that seems to work as expected. Great!
Thanks a lot for implementing the feature!
